name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.HOSTINGER_USERNAME }}
        PASSWORD: ${{ secrets.HOSTINGER_PASSWORD }}
        PORT: ${{ secrets.PORT }}
      with:
        source: "."
        target: "/var/www/marchawkins_usr/data/www/kc3dfx.com"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      with:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.HOSTINGER_USERNAME }}
        PASSWORD: ${{ secrets.HOSTINGER_PASSWORD }}
        PORT: ${{ secrets.PORT }}
        script: ls